### ISSUE TITLE
How to handle removing (x) the chip?

### ISSUE THREAD

**Issue by 5amfung** [Collaborne/paper-chip#1]
Do you have any documentation on how to handle removing the chip by click on the x?  Thanks.

**Comment by ronnyroeller** [comment]
Have a look to the demo for `paper-chips`:
http://collaborne.github.io/paper-chip/components/paper-chip/#paper-chips (click the demo link in the upper right corner)

Here is the code: https://github.com/Collaborne/paper-chip/blob/master/demo/chips.html
