### ISSUE TITLE
Migrate to Polymer 3

### ISSUE THREAD

**Issue by RoXuS** [Collaborne/paper-chip#7]
Hello !

We use it our component since 2016 (thx) and we want migrate to Polymer 3.

Did you plan to migrate on it?
Would you accept a PR from me about this?

**Comment by ronnyroeller** [comment]
Hi @RoXuS - we don't have a fixed schedule when we will migrate to Polymer 3. But sure, we'd execpt a PR.

**Comment by srijken** [comment]
Note that html-imports will stop being support in Chrome starting March 2019.

I'll see if I can come up with a PR

**Comment by ronnyroeller** [comment]
Element has been migrated to Polymer 3
